# Generated by Django 2.1.15 on 2020-04-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='service',
            table='Service',
        ),
    ]
