# Generated by Django 2.1.15 on 2020-04-24 20:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 20, 25, 7, 108122, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
